development:
  #adapter: async
  #adapter: redis
  adapter: redis

test:
  adapter: async

production:
  adapter: redis
  #adapter: any_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: hermes_production
